import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService, AuthResponse } from '../services/auth.service';
import { ToastService } from '../services/toast.service';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent {
  currentStep = 1;
  totalSteps = 4;

  formData = {
    name: '',
    email: '',
    userType: '', // 'single' or 'group'
    groupPasskey: '', // For group users (required pattern: XXXX-XXXX)
    role: '', // 'leader' or 'member' (only for group)
    accessKey: '', // For members to join group
    tempAccessKey: '', // For leaders (preview before submission)
    generatedAccessKey: '', // For leaders (generated by backend)
    password: '',
    confirmPassword: '',
  };

  isLoading = false;
  showPassword = false;
  showConfirmPassword = false;

  constructor(
    private authService: AuthService,
    private router: Router,
    private toastService: ToastService
  ) {}

  togglePasswordVisibility(field: 'password' | 'confirmPassword') {
    if (field === 'password') {
      this.showPassword = !this.showPassword;
    } else {
      this.showConfirmPassword = !this.showConfirmPassword;
    }
  }

  nextStep() {
    if (this.validateCurrentStep()) {
      // Skip role selection if single user
      if (this.currentStep === 2 && this.formData.userType === 'single') {
        this.currentStep = 4; // Go directly to password
      } else {
        this.currentStep++;
      }
    }
  }

  previousStep() {
    // Skip role selection when going back from password for single users
    if (this.currentStep === 4 && this.formData.userType === 'single') {
      this.currentStep = 2;
    } else {
      this.currentStep--;
    }
  }

  selectUserType(type: 'single' | 'group') {
    this.formData.userType = type;
    // Reset group-specific fields when switching
    if (type === 'single') {
      this.formData.groupPasskey = '';
      this.formData.role = '';
      this.formData.tempAccessKey = '';
    }
  }

  formatPasskey(event: any) {
    let value = event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '');

    // Add hyphen after 4 characters
    if (value.length > 4) {
      value = value.slice(0, 4) + '-' + value.slice(4, 8);
    }

    this.formData.groupPasskey = value;
  }

  validatePasskeyPattern(passkey: string): boolean {
    // Pattern: XXXX-XXXX (4 alphanumeric, hyphen, 4 alphanumeric)
    const pattern = /^[A-Z0-9]{4}-[A-Z0-9]{4}$/;
    return pattern.test(passkey);
  }

  getPasskeyStrength(): number {
    const passkey = this.formData.groupPasskey.replace('-', '');
    if (passkey.length === 0) return 0;

    let strength = 0;

    // Length check
    if (passkey.length >= 8) strength += 40;
    else strength += (passkey.length / 8) * 40;

    // Has letters
    if (/[A-Z]/.test(passkey)) strength += 30;

    // Has numbers
    if (/[0-9]/.test(passkey)) strength += 30;

    return Math.min(100, strength);
  }

  getPasskeyStrengthText(): string {
    const strength = this.getPasskeyStrength();
    if (strength < 50) return '⚠️ Weak - Add more variety';
    if (strength < 80) return '✓ Medium - Good mix';
    return '✓✓ Strong - Excellent!';
  }

  selectRole(role: 'leader' | 'member') {
    this.formData.role = role;
    // Reset temp access key when switching roles
    this.formData.tempAccessKey = '';
  }

  generateAccessKey() {
    // Generate a random 8-character access key
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let key = '';
    for (let i = 0; i < 8; i++) {
      key += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    this.formData.tempAccessKey = key;
    this.toastService.show('Access key created! 🎉', 'success');
  }

  validateCurrentStep(): boolean {
    switch (this.currentStep) {
      case 1:
        // Validate name and email
        if (!this.formData.name || !this.formData.email) {
          this.toastService.show('Please enter your name and email', 'error');
          return false;
        }
        if (this.formData.name.length < 2) {
          this.toastService.show('Name must be at least 2 characters', 'error');
          return false;
        }
        const emailRegex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
        if (!emailRegex.test(this.formData.email)) {
          this.toastService.show('Please enter a valid email', 'error');
          return false;
        }
        return true;

      case 2:
        // Validate user type selection
        if (!this.formData.userType) {
          this.toastService.show('Please select a user type', 'error');
          return false;
        }
        return true;

      case 3:
        // Validate role selection for group users
        if (this.formData.userType === 'group') {
          if (!this.formData.role) {
            this.toastService.show('Please select your role', 'error');
            return false;
          }
          if (this.formData.role === 'leader' && !this.formData.tempAccessKey) {
            this.toastService.show('Please create an access key', 'error');
            return false;
          }
          if (this.formData.role === 'member' && !this.formData.accessKey) {
            this.toastService.show('Please enter the access key', 'error');
            return false;
          }
        }
        return true;

      case 4:
        // Validate password
        if (!this.formData.password || !this.formData.confirmPassword) {
          this.toastService.show('Please enter and confirm password', 'error');
          return false;
        }
        if (this.formData.password.length < 6) {
          this.toastService.show(
            'Password must be at least 6 characters',
            'error'
          );
          return false;
        }
        if (this.formData.password !== this.formData.confirmPassword) {
          this.toastService.show('Passwords do not match', 'error');
          return false;
        }
        return true;

      default:
        return true;
    }
  }

  validateForm(): boolean {
    return this.validateCurrentStep();
  }

  onSubmit() {
    if (!this.validateForm()) {
      return;
    }

    this.isLoading = true;

    const userData: any = {
      name: this.formData.name,
      email: this.formData.email,
      password: this.formData.password,
      userType: this.formData.userType,
    };

    // Add role and accessKey for group users
    if (this.formData.userType === 'group') {
      userData.role = this.formData.role;

      if (this.formData.role === 'member') {
        // Member uses access key to join group
        userData.accessKey = this.formData.accessKey;
      } else if (this.formData.role === 'leader') {
        // Leader creates group with access key
        userData.accessKey = this.formData.tempAccessKey;
      }
    }

    console.log('📤 Sending signup data:', {
      ...userData,
      password: '***',
    });

    this.authService.signup(userData).subscribe({
      next: (response: AuthResponse) => {
        this.isLoading = false;

        console.log('✅ Signup response:', response);

        // If leader, show access key
        if (response.user?.accessKey) {
          this.formData.generatedAccessKey = response.user.accessKey;
          this.toastService.show(
            `Account created! Your access key: ${response.user.accessKey}`,
            'success',
            10000
          );
        } else {
          this.toastService.show('Account created successfully! 🎉', 'success');
        }

        // Store user data
        localStorage.setItem('kanban_user', JSON.stringify(response.user));

        // Redirect to board after delay
        setTimeout(
          () => {
            this.router.navigate(['/board']);
          },
          response.user?.accessKey ? 8000 : 1500
        );
      },
      error: (error: any) => {
        this.isLoading = false;
        const errorMessage =
          error.error?.message || 'Registration failed. Please try again.';
        this.toastService.show(errorMessage, 'error');
      },
    });
  }
}
